services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: debezium/postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo

  kafka-connect:
    image: debezium/connect:2.7.3.Final
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets
      STATUS_STORAGE_TOPIC: my-connect-status
    ports:
      - "8083:8083"
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - kafka-connect
      - postgres
    ports:
      - "8080:8080"
      
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
networks:
  app-net:
    driver: bridge